FROM rust:1.70-alpine as prereq
RUN apk add --no-cache musl-dev mingw-w64-gcc
RUN rustup target add x86_64-pc-windows-gnu


FROM prereq as build

WORKDIR /src
COPY . /src
RUN cargo build --target x86_64-pc-windows-gnu --release


FROM scratch as output
COPY --from=build /src/target/x86_64-pc-windows-gnu/release/mskey.exe /mskey.exe
